version: '3.1'
networks:
  net:
services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: diplom_user
      POSTGRES_DB: diplom_db
    networks:
      - net
    ports:
      - "5433:5432"

  app:
    build: .
    networks:
      - net
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - '6379:6379'

  # celery:
  #   build: .
  #   command: celery -A orders worker
  #   depends_on:
  #     - redis
