version: '3.9'
networks:
  net:
services:
  postgredb:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: diplom_user
      POSTGRES_DB: diplom_db
    networks:
      - net
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app-c
    networks:
      - net
    ports:
      - "8000:8000"
    depends_on:
      - postgredb

  redis:
    image: redis
    ports:
      - '6379:6379'

  # celery:
  #   build: .
  #   command: celery -A orders worker
  #   depends_on:
  #     - redis
